setwd(old.dir)
ls()
dir()
list.files()
?list.files
args(list.files)
old.dir <- dir()
old.dir<-getwd()
dir.create("testdir")
setwd("testdir")
file.create("mytest.R")
dir()
file.exists("mytest,R")
file.info("mytest.R")
file.rename("mytest.r", "mytest2.R")
file.copy("mytest2.R", "mytest3.R")
file.path("mytest3.R")
?dir.create
dir.create(file.path("testdir2", "testdir3"), recursive = TRUE)
setwd(old.dir)
